### ISSUE TITLE
no colormap.json in checkpoint_dir

### ISSUE THREAD

**Issue by bubbleyang111** [cj-mills/pytorch-yolox-object-detection-tutorial-code#1]
notebooks/pytorch-yolox-object-detector-onnx-export.ipynb: https://christianjmills.com/posts/pytorch-train-object-detector-yolox-tutorial/onnx-export/#load-the-colormap

**Comment by cj-mills** [comment]
Hi @bubbleyang111,

The ONNX export tutorial and its associated notebook assume you have completed part 1 of the tutorial series:

- [Training YOLOX Models for Real-Time Object Detection in PyTorch](https://christianjmills.com/posts/pytorch-train-object-detector-yolox-tutorial/)

Here is the section in part 1 where we save the JSON colormap file:

- [Save the Color Map](https://christianjmills.com/posts/pytorch-train-object-detector-yolox-tutorial/#save-the-color-map)

You then update the path to the checkpoint folder in the ONNX export tutorial/notebook in this section:

- [Set the Directory Paths](https://christianjmills.com/posts/pytorch-train-object-detector-yolox-tutorial/onnx-export/#set-the-directory-paths)

If you did not complete the training tutorial, you can download sample colormap, model, and normalization stats files from the following HuggingFace Hub repository:

- [cj-mills/yolox-hagrid-pytorch](https://huggingface.co/cj-mills/yolox-hagrid-pytorch/tree/main)

**Comment by bubbleyang111** [comment]
OK, thanks.
